{% set name = "pdr" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdr-{{ version }}.tar.gz
  sha256: f78ab41d90a55f3d8c2fee639499ef50f33333878170f1d2b63715f8bddeb45b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - astropy
    - cytoolz
    - dustgoggles
    - matplotlib-base
    - more-itertools
    - multidict
    - numpy
    - pandas
    - pds4_tools
    - pillow
    - pvl
    - python >=3.9
    - python-levenshtein

test:
  imports:
    - pdr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MillionConcepts/pdr
  summary: A simple library to read all planetary data.
  description: pdr, the Planetary Data Reader, is a tool which provides a single command -- read('/path/to/file') -- for ingesting all common planetary data types.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
