{% set name = "pdr" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdr-{{ version }}.tar.gz
  sha256: 2e921294a81c453cde235ee94d6ef3ef3df371762454b1eceabcd520dd009891

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - astropy
    - cytoolz
    - dustgoggles
    - more-itertools
    - multidict
    - numpy
    - pandas >=2.0.0
    - pillow
    - pvl
    - python >={{ python_min }}
    - rms-vax

test:
  imports:
    - pdr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MillionConcepts/pdr
  summary: A simple library to read all planetary data.
  description: pdr, the Planetary Data Reader, is a tool which provides a single command -- read('/path/to/file') -- for ingesting all common planetary data types.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - Sierra-MC
