{% set name = "pdr" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdr-{{ version }}.tar.gz
  sha256: 4301d539643c628fab1dd7d76e1e4d33f0842df514db32527e63de767550a3a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - astropy
    - dustgoggles
    - more-itertools
    - matplotlib-base
    - multidict
    - numpy
    - pandas
    - pds4_tools
    - pillow
    - pvl
    - python >=3.9
    - python-levenshtein

test:
  imports:
    - pdr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MillionConcepts/pdr
  summary: A simple library to read all planetary data.
  description: pdr, the Planetary Data Reader, is a tool which provides a single command -- read('/path/to/file') -- for ingesting all common planetary data types.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
